#JDBC

#API,SQLDRIVER, myComputer, PORT, MY DATABASE NAME
db.url=jdbc:mysql://localhost:3306/banking_db?useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true
db.username=root
db.password=
